name: Deploy ASP.NET Core WebApi to Azure App Service

on:
  push:
    branches:
      - main 

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore WebApi/WebApi.csproj

      - name: Build
        run: dotnet build WebApi/WebApi.csproj --configuration Release --no-restore

      - name: Publish
        run: dotnet publish WebApi/WebApi.csproj --configuration Release --output ./publish --no-restore

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ES-Academy      
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ./publish
